### ISSUE TITLE
AttributeError: module 'errno' has no attribute 'ENODATA'

### ISSUE THREAD

**Issue by teknsl** [thingalon/pony-ssh#32]
Host Windows 10
Remote OpenBSD 7.0
VSCodium 1.66.2
PonySSH 1.5.0 (Open VSX)
Remote Python 3.8.12

```json
"ponyssh.hosts": {
  "homelab": {
    "host": "remote",
    "username": "user",
    "password": true,
    "python": "/usr/local/bin/python3"
  }
}
```

```
[2022-04-13 22:48:40] [info] Connecting to homelab: {
  host: 'remote',
  username: 'user',
  password: '*****',
  python: '/usr/local/bin/python3'
}
[2022-04-13 22:48:40] [info] Connection established
[2022-04-13 22:48:40] [info] Preparing worker script
[2022-04-13 22:48:40] [info] Worker script ok
[2022-04-13 22:48:40] [info] Opening workers
[2022-04-13 22:48:41] [info] Remote home directory: /home/user/
[2022-04-13 22:48:41] [info] Connected to homelab
[2022-04-13 22:48:41] [warn] Channel STDERR output: Traceback (most recent call last):
  File "/home/user/.pony-ssh/worker.zip/__main__.py", line 38, in run_worker
  File "/home/user/.pony-ssh/worker.zip/handlers.py", line 102, in handle_file_read
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.vscode/settings.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.pony-ssh/worker.zip/__main__.py", line 55, in <module>
  File "/home/user/.pony-ssh/worker.zip/__main__.py", line 45, in run_worker
  File "/home/user/.pony-ssh/worker.zip/errors.py", line 46, in process_error
AttributeError: module 'errno' has no attribute 'ENODATA'

[2022-04-13 22:48:41] [error] Connection error: Unexpected end of worker channel
[2022-04-13 22:48:41] [error] Connection error: Unexpected end of worker channel
[2022-04-13 22:48:41] [error] Connection error: Unexpected end of worker channel
[2022-04-13 22:48:41] [error] Connection error: Unexpected end of worker channel
[2022-04-13 22:48:41] [error] Connection error: Unexpected end of worker channel
```

copying over settings.json from the host changes the error to task.json; so creating all of vscode's configs (not tested yet) would probably fix this issue but it could affect other things. I don't think my Linux remote needed vscode configs (and crashed alongside it) but i could be wrong as it has been a while and i don't have it anymore

**Comment by teknsl** [comment]
Stale.
